### ISSUE TITLE
Can this plugins and your main software be used with plesk without any issue?

### ISSUE THREAD

**Issue by gelsas** [syncgw/roundcube-select_for_sync#1]
Can this plugins and your main software be used with plesk without any issue? (https://www.plesk.com/)

To have something like sync*gw with all its features easily installable via Plesk Extensions would be a gamechanger. (https://www.plesk.com/extensions/)
It is much requested: https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/3968986-activesync-support-on-roundcube-and-horde-push

I think if you would offer your software as an Plesk Extension (with a one time fee like 100€ or something like that) you would get a lot of customers (me being one of them)

**Comment by syncgw** [comment]
Thank you for your great suggestion. We will check, if we can provide such a solution and let you know.

**Comment by syncgw** [comment]
Hi, we contacted Plesk and got a trail license. We do not have any internet server (Unix Win) where we can install Plesk, so we tried Win10 and WSL. Plesk does not work on these platforms. Contacting Plesk again. The company do not offer any sand boxes. At the end of the day we do not have a development environment to create a Plex extension :-(
