### ISSUE TITLE
Unable to contact

### ISSUE THREAD

**Issue by jarrodjay** [syncgw/roundcube-select_for_sync#2]
Hello,
Sorry for creating an issue here, but it's necessary. I've purchased your syncgw software through syncgw.com, however, your contact form and email address bounce back saying your inbox is unmonitored. How do I get in contact with you to receive my software?
Thank you.

**Comment by syncgw** [comment]
Hi,
we just proceed your purchase order and will get in touch with you asap.

**Comment by syncgw** [comment]
We tried to contact you. Unfortunately we got an error:

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [jarr***@***.com](mailto:jarr***@***.com)
    host aspmx.l.google.com [74.125.140.27]
    SMTP error from remote mail server after end of data:
    552-5.7.0 This message was blocked because its content presents a potential
    552-5.7.0 security issue. Please visit
    552-5.7.0  https://support.google.com/mail/?p=BlockedMessage to review our
    552 5.7.0 message content and attachment content guidelines. c9-20020a056000184900b0020cfdc05b3esi11561614wri.673 - gsmtp

Since blocking came by your mail server please check you Spam folder or ask your provider how to come out of the mess.

**Comment by syncgw** [comment]
We fixed download server problem. You should now be able (after login) to download your purchased software.

**Comment by jarrodjay** [comment]
Thank you! I'm able to download now. Do you provide receipts at all?

**Comment by jarrodjay** [comment]
Hi again. How do I contact for help? The FAQ and support forum mentioned in the Readme are 404.
I'm having a technical issue.

**Comment by jarrodjay** [comment]
It'd be great if I could please get an answer, or someone of contacting you via email. Your software is having issues on our server. When running the environment check, I'm getting a 500 error. When disabling the "syncgw\dav\DAV_Handler" check, its succeeding correctly. I'm unable to pin point what the issue is. Furthermore, once the environment check proceeds fine (without the DAV_Handler at the moment), what's the next step? As your FAQ is down, I'm a bit stumped.

Thank you.
